# jlpt_data.py — Vocabulary & grammar pattern database (extracted from jlpt.py)
# This module is imported by jlpt.py

JLPT_DATA = {
    "n5": [
        {"word": "こんにちは", "reading": "こんにちは", "meaning": "hello", "type": "greeting"},
        {"word": "おはよう",   "reading": "おはよう",   "meaning": "good morning", "type": "greeting"},
        {"word": "こんばんは", "reading": "こんばんは", "meaning": "good evening", "type": "greeting"},
        {"word": "さようなら", "reading": "さようなら", "meaning": "goodbye", "type": "greeting"},
        {"word": "ありがとう", "reading": "ありがとう", "meaning": "thank you", "type": "greeting"},
        {"word": "すみません", "reading": "すみません", "meaning": "excuse me", "type": "greeting"},
        {"word": "はい",       "reading": "はい",       "meaning": "yes", "type": "response"},
        {"word": "いいえ",     "reading": "いいえ",     "meaning": "no", "type": "response"},
        {"word": "人",   "reading": "ひと",   "meaning": "person", "type": "noun"},
        {"word": "水",   "reading": "みず",   "meaning": "water",  "type": "noun"},
        {"word": "山",   "reading": "やま",   "meaning": "mountain","type": "noun"},
        {"word": "川",   "reading": "かわ",   "meaning": "river",  "type": "noun"},
        {"word": "海",   "reading": "うみ",   "meaning": "sea",    "type": "noun"},
        {"word": "空",   "reading": "そら",   "meaning": "sky",    "type": "noun"},
        {"word": "花",   "reading": "はな",   "meaning": "flower", "type": "noun"},
        {"word": "木",   "reading": "き",     "meaning": "tree",   "type": "noun"},
        {"word": "本",   "reading": "ほん",   "meaning": "book",   "type": "noun"},
        {"word": "電話", "reading": "でんわ", "meaning": "telephone","type": "noun"},
        {"word": "電車", "reading": "でんしゃ","meaning": "train",  "type": "noun"},
        {"word": "駅",   "reading": "えき",   "meaning": "station","type": "noun"},
        {"word": "病院", "reading": "びょういん","meaning": "hospital","type": "noun"},
        {"word": "学校", "reading": "がっこう","meaning": "school", "type": "noun"},
        {"word": "家",   "reading": "いえ",   "meaning": "house",  "type": "noun"},
        {"word": "今日", "reading": "きょう", "meaning": "today",  "type": "noun"},
        {"word": "明日", "reading": "あした", "meaning": "tomorrow","type": "noun"},
        {"word": "昨日", "reading": "きのう", "meaning": "yesterday","type": "noun"},
        {"word": "朝",   "reading": "あさ",   "meaning": "morning","type": "noun"},
        {"word": "昼",   "reading": "ひる",   "meaning": "noon",   "type": "noun"},
        {"word": "夜",   "reading": "よる",   "meaning": "night",  "type": "noun"},
        {"word": "一",   "reading": "いち",   "meaning": "one",    "type": "number"},
        {"word": "二",   "reading": "に",     "meaning": "two",    "type": "number"},
        {"word": "三",   "reading": "さん",   "meaning": "three",  "type": "number"},
        {"word": "食べる","reading": "たべる", "meaning": "to eat", "type": "verb"},
        {"word": "飲む", "reading": "のむ",   "meaning": "to drink","type": "verb"},
        {"word": "見る", "reading": "みる",   "meaning": "to see", "type": "verb"},
        {"word": "話す", "reading": "はなす", "meaning": "to speak","type": "verb"},
        {"word": "書く", "reading": "かく",   "meaning": "to write","type": "verb"},
        {"word": "読む", "reading": "よむ",   "meaning": "to read", "type": "verb"},
        {"word": "行く", "reading": "いく",   "meaning": "to go",  "type": "verb"},
        {"word": "来る", "reading": "くる",   "meaning": "to come","type": "verb"},
        {"word": "する", "reading": "する",   "meaning": "to do",  "type": "verb"},
        {"word": "帰る", "reading": "かえる", "meaning": "to return","type": "verb"},
        {"word": "大きい","reading": "おおきい","meaning": "big",    "type": "adjective"},
        {"word": "小さい","reading": "ちいさい","meaning": "small",  "type": "adjective"},
        {"word": "新しい","reading": "あたらしい","meaning": "new",  "type": "adjective"},
        {"word": "古い", "reading": "ふるい",  "meaning": "old",    "type": "adjective"},
        {"word": "高い", "reading": "たかい",  "meaning": "high/expensive","type": "adjective"},
        {"word": "難しい","reading": "むずかしい","meaning": "difficult","type": "adjective"},
        {"word": "面白い","reading": "おもしろい","meaning": "interesting","type": "adjective"},
        {"word": "美味しい","reading": "おいしい","meaning": "delicious","type": "adjective"},
    ],
    "n4": [
        {"word": "勉強", "reading": "べんきょう","meaning": "study",    "type": "noun"},
        {"word": "料理", "reading": "りょうり",  "meaning": "cooking",  "type": "noun"},
        {"word": "約束", "reading": "やくそく",  "meaning": "promise",  "type": "noun"},
        {"word": "計画", "reading": "けいかく",  "meaning": "plan",     "type": "noun"},
        {"word": "準備", "reading": "じゅんび",  "meaning": "preparation","type": "noun"},
        {"word": "説明", "reading": "せつめい",  "meaning": "explanation","type": "noun"},
        {"word": "練習", "reading": "れんしゅう","meaning": "practice", "type": "noun"},
        {"word": "経験", "reading": "けいけん",  "meaning": "experience","type": "noun"},
        {"word": "問題", "reading": "もんだい",  "meaning": "problem",  "type": "noun"},
        {"word": "質問", "reading": "しつもん",  "meaning": "question", "type": "noun"},
        {"word": "意味", "reading": "いみ",      "meaning": "meaning",  "type": "noun"},
        {"word": "仕事", "reading": "しごと",    "meaning": "work",     "type": "noun"},
        {"word": "会議", "reading": "かいぎ",    "meaning": "meeting",  "type": "noun"},
        {"word": "調べる","reading": "しらべる", "meaning": "to investigate","type": "verb"},
        {"word": "忘れる","reading": "わすれる", "meaning": "to forget","type": "verb"},
        {"word": "変わる","reading": "かわる",   "meaning": "to change","type": "verb"},
        {"word": "便利",  "reading": "べんり",   "meaning": "convenient","type": "adjective"},
        {"word": "危険",  "reading": "きけん",   "meaning": "dangerous","type": "adjective"},
        {"word": "安全",  "reading": "あんぜん", "meaning": "safe",     "type": "adjective"},
        {"word": "簡単",  "reading": "かんたん", "meaning": "simple",   "type": "adjective"},
        {"word": "重要",  "reading": "じゅうよう","meaning": "important","type": "adjective"},
        {"word": "必要",  "reading": "ひつよう", "meaning": "necessary","type": "adjective"},
    ],
    "n3": [
        {"word": "努力",  "reading": "どりょく", "meaning": "effort",      "type": "noun"},
        {"word": "原因",  "reading": "げんいん", "meaning": "cause",       "type": "noun"},
        {"word": "効果",  "reading": "こうか",   "meaning": "effect",      "type": "noun"},
        {"word": "目的",  "reading": "もくてき", "meaning": "purpose",     "type": "noun"},
        {"word": "状態",  "reading": "じょうたい","meaning": "state",      "type": "noun"},
        {"word": "関係",  "reading": "かんけい", "meaning": "relationship","type": "noun"},
        {"word": "理解",  "reading": "りかい",   "meaning": "understanding","type": "noun"},
        {"word": "研究",  "reading": "けんきゅう","meaning": "research",   "type": "noun"},
        {"word": "開発",  "reading": "かいはつ", "meaning": "development", "type": "noun"},
        {"word": "改善",  "reading": "かいぜん", "meaning": "improvement", "type": "noun"},
        {"word": "解決",  "reading": "かいけつ", "meaning": "solution",    "type": "noun"},
        {"word": "感じる","reading": "かんじる", "meaning": "to feel",     "type": "verb"},
        {"word": "考える","reading": "かんがえる","meaning": "to think",   "type": "verb"},
        {"word": "信じる","reading": "しんじる", "meaning": "to believe",  "type": "verb"},
        {"word": "具体的","reading": "ぐたいてき","meaning": "specific",   "type": "adjective"},
        {"word": "客観的","reading": "きゃくかんてき","meaning": "objective","type": "adjective"},
        {"word": "主観的","reading": "しゅかんてき","meaning": "subjective","type": "adjective"},
    ],
    "n2": [
        {"word": "発展",   "reading": "はってん",   "meaning": "development",    "type": "noun"},
        {"word": "改革",   "reading": "かいかく",   "meaning": "reform",         "type": "noun"},
        {"word": "戦略",   "reading": "せんりゃく", "meaning": "strategy",       "type": "noun"},
        {"word": "政策",   "reading": "せいさく",   "meaning": "policy",         "type": "noun"},
        {"word": "対策",   "reading": "たいさく",   "meaning": "countermeasure", "type": "noun"},
        {"word": "革新的", "reading": "かくしんてき","meaning": "innovative",    "type": "adjective"},
        {"word": "総合的", "reading": "そうごうてき","meaning": "comprehensive", "type": "adjective"},
        {"word": "一時的", "reading": "いちじてき", "meaning": "temporary",      "type": "adjective"},
        {"word": "強化",   "reading": "きょうか",   "meaning": "to strengthen",  "type": "verb"},
        {"word": "促進",   "reading": "そくしん",   "meaning": "to promote",     "type": "verb"},
    ],
    "n1": [
        {"word": "統合",   "reading": "とうごう",   "meaning": "integration",      "type": "noun"},
        {"word": "体系化", "reading": "たいけいか", "meaning": "systematization",  "type": "noun"},
        {"word": "構造化", "reading": "こうぞうか", "meaning": "structuring",      "type": "noun"},
        {"word": "多様化", "reading": "たようか",   "meaning": "diversification",  "type": "noun"},
        {"word": "標準化", "reading": "ひょうじゅんか","meaning": "standardization","type": "noun"},
        {"word": "包括的", "reading": "ほうかつてき","meaning": "comprehensive",   "type": "adjective"},
        {"word": "革命的", "reading": "かくめいてき","meaning": "revolutionary",   "type": "adjective"},
        {"word": "変容",   "reading": "へんよう",   "meaning": "to transform",     "type": "verb"},
        {"word": "精緻化", "reading": "せいちか",   "meaning": "to refine",        "type": "verb"},
        {"word": "明確化", "reading": "めいかくか", "meaning": "to clarify",       "type": "verb"},
    ],
}

GRAMMAR_PATTERNS = {
    "n5": [
        {"pattern": "です",         "meaning": "is / am / are (polite)", "level": "n5"},
        {"pattern": "ます",         "meaning": "polite verb ending",      "level": "n5"},
        {"pattern": "ません",       "meaning": "polite negative",         "level": "n5"},
        {"pattern": "ました",       "meaning": "polite past",             "level": "n5"},
        {"pattern": "たい",         "meaning": "want to",                 "level": "n5"},
        {"pattern": "ている",       "meaning": "progressive",             "level": "n5"},
        {"pattern": "てください",   "meaning": "please do",               "level": "n5"},
        {"pattern": "ましょう",     "meaning": "let's",                   "level": "n5"},
        {"pattern": "ことができる", "meaning": "can / able to",           "level": "n5"},
    ],
    "n4": [
        {"pattern": "なければならない","meaning": "must",                 "level": "n4"},
        {"pattern": "はずだ",       "meaning": "should be / expected to", "level": "n4"},
        {"pattern": "そうだ",       "meaning": "looks like / I heard",    "level": "n4"},
        {"pattern": "ようだ",       "meaning": "it seems",                "level": "n4"},
        {"pattern": "らしい",       "meaning": "seems like",              "level": "n4"},
    ],
    "n3": [
        {"pattern": "べきだ",       "meaning": "should / ought to",       "level": "n3"},
        {"pattern": "ために",       "meaning": "in order to",             "level": "n3"},
        {"pattern": "ながら",       "meaning": "while doing",             "level": "n3"},
        {"pattern": "のに",         "meaning": "despite / although",      "level": "n3"},
    ],
    "n2": [
        {"pattern": "にもかかわらず","meaning": "despite / regardless",  "level": "n2"},
        {"pattern": "に対して",     "meaning": "in relation to",          "level": "n2"},
        {"pattern": "をはじめ",     "meaning": "starting with",           "level": "n2"},
    ],
    "n1": [
        {"pattern": "にほかならない","meaning": "nothing but",            "level": "n1"},
        {"pattern": "をもって",     "meaning": "by means of",             "level": "n1"},
        {"pattern": "いかん",       "meaning": "depending on",            "level": "n1"},
    ],
}
